site_name: Adam Test
site_description: Starter template for a MkDocs docs site on GH Pages - including CI

theme: dracula

nav:
  - Home: index.md
  - Folder:
      - Page 1: pages/page_1.md
      - Page 2: pages/page_2.md

plugins:
  - search
  - mermaid2

